-- H2-compatible test schema (quote reserved table names like "user")
CREATE TABLE IF NOT EXISTS "user" (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(100),
	phone VARCHAR(20),
	role VARCHAR(20) NOT NULL DEFAULT 'STUDENT',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	student_number VARCHAR(20) NOT NULL UNIQUE,
	name VARCHAR(50) NOT NULL,
	clazz VARCHAR(50),
	major VARCHAR(100),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	credit DECIMAL(3,1) NOT NULL,
	teacher_name VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS score (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	student_id BIGINT NOT NULL,
	course_id BIGINT NOT NULL,
	value DECIMAL(5,2) NOT NULL,
	recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS score_history (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	score_id BIGINT NOT NULL,
	before_value DECIMAL(5,2),
	after_value DECIMAL(5,2) NOT NULL,
	modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
